steps:
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      echo "$GOOGLE_CLOUD_CREDENTIALS" > /workspace/service-account-key.json
      python3 -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate

    # 각 단계별로 시간 제한을 지정할 수 있습니다.
    timeout: '1600s'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

    # 각 단계별로 시간 제한을 지정할 수 있습니다.
    timeout: '1600s'

secrets:
- secretEnv:
    GOOGLE_CLOUD_CREDENTIALS: projects/535442247184/secrets/service-account-key/versions/latest

service_account: 535442247184-compute@developer.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'