steps:
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      # Secret Manager에서 가져온 비밀을 디코딩하지 않고 출력하여 원본을 확인
      echo "Original Base64 Encoded GOOGLE_CLOUD_CREDENTIALS:"
      echo "$GOOGLE_CLOUD_CREDENTIALS"
      
      # Base64로 디코딩하여 파일로 저장
      echo "$GOOGLE_CLOUD_CREDENTIALS" | base64 --decode > /workspace/service-account-key.json
      
      # 디코딩된 파일의 내용을 확인
      echo "Decoded service-account-key.json:"
      cat /workspace/service-account-key.json
      
      # 가상환경 생성 및 활성화
      python3 -m venv venv
      . venv/bin/activate
      
      # 필요한 패키지 설치
      pip install -r requirements.txt
      
      # 정적 파일 수집 및 마이그레이션
      python manage.py collectstatic --noinput
      python manage.py migrate

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

secrets:
- secretEnv:
    GOOGLE_CLOUD_CREDENTIALS: projects/535442247184/secrets/service-account-key/versions/latest

service_account: 535442247184-compute@developer.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'